// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBimNdKR_CH530MLUmgXqWD70b_QeaXF0A',
    appId: '1:215549519800:web:5a4530ac9d636860fe114d',
    messagingSenderId: '215549519800',
    projectId: 'gptutor-f2a34',
    authDomain: 'gptutor-f2a34.firebaseapp.com',
    storageBucket: 'gptutor-f2a34.appspot.com',
    measurementId: 'G-D2G1SRJH2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACOs6yLIdtNz-8WK2qe4TSPPUZOAbSujk',
    appId: '1:215549519800:android:2629ca0a6b06209dfe114d',
    messagingSenderId: '215549519800',
    projectId: 'gptutor-f2a34',
    storageBucket: 'gptutor-f2a34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZuEQweNOvdgnUpUfs-VCToPcxFfXudrY',
    appId: '1:215549519800:ios:af96da58c75357f3fe114d',
    messagingSenderId: '215549519800',
    projectId: 'gptutor-f2a34',
    storageBucket: 'gptutor-f2a34.appspot.com',
    iosClientId: '215549519800-ift4ktrgjgknb3qnql4rra471sb9c90k.apps.googleusercontent.com',
    iosBundleId: 'com.example.gptutor',
  );
}
